version: "3"

services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            - SA_PASSWORD=${DB_PASSWORD}
            - ACCEPT_EULA=Y
            - TZ=${TZ}
        volumes:
            - database-vol:/var/opt/mssql
        ports:
            - 1433:1433

    nginx:
        build:
            context: ./docker/nginx
        depends_on:
            - php
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - ${NGINX_HOST_HTTPS_PORT}:443
            - ${NGINX_HOST_HTTP_PORT}:80

    php:
        build:
            context: ./docker/php-fpm
            args:
                TIMEZONE: ${TZ}
        depends_on:
            - db
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        expose:
            - 9000

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - ${FORWARD_MAILHOG_PORT:-1025}:1025
            - ${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025

volumes:
    database-vol:
